### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by demattosanthony** [syyclops/brontes#116]
We need a nice interface for the documentation of this project. We need docs on both what the project is and how it works as well as an api reference.

I think we should use [this](https://docusaurus.io/). You can check and see if you like anything better

Some good docs page examples:

https://platform.openai.com/docs/overview
https://developers.willowinc.com/openapi/willowtwin/v2/

**Comment by monicasuresh** [comment]
will work on it

**Comment by monicasuresh** [comment]
using mkdocs for documentation for brontes api
