### ISSUE TITLE
Kaiterra Integration

### ISSUE THREAD

**Issue by olegault** [syyclops/brontes#129]
- [ ] Retrieve messages using hivemq and existing methods
- [ ] Display the timeseries data through api docs
- [ ] Return the messages as cleaned data that distinguishes the timestamp and different tracked values (temperature, CO2, etc)

**Comment by demattosanthony** [comment]
@olegault consolidating the kaiterra issues here: 

Right now the points are all within a single message in this format:

{"ts":1717691024,"dsn":"VG21D16414","dudid":"5e81563a-42ca-4137-9b36-f423a6f27a73","units":{"temperature":"C","humidity":"%","pm25":"ug/m3","pm10":"ug/m3","co2":"ppm","tvoc":"ppb"},"data":{"temperature":24.37,"humidity":50.38,"pm25":1,"pm10":1,"co2":963,"tvoc":35}}

We need a method to extract each point (temperature, humidity, co2, ppm, tvoc, etc) and its corresponding value from each message.

Point | Value
{ Temp | 24.37 }
{ Humidity | 50.38 }
{ TVOC | 35 }
